# Generated by Django 4.1.2 on 2022-10-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
